initial release
aleXOR2/pytest-pylint-xdist-vcs pull request #1
Opened 2019-11-25 14:14 UTC by aleXOR2

@mikitachab please review

2019-12-10 10:02 UTC, mikitachab requested changes

2019-12-10 10:02 UTC, mikitachab commented on README.md
> +>>>>>>> initial release
git merge rubbish????

2019-12-11 14:18 UTC, mikitachab commented on README.md
> +* Python3.5+
Python3.5+ -> Python 3.5+

2019-12-11 14:18 UTC, mikitachab commented on test/test_pytest_pylint_xdist_vcs.py
> +TRUE = True
?

2019-12-11 14:18 UTC, mikitachab commented on .pre-commit-config.yaml
> +        language_version: python3.6
README says Python 3.5+

2019-12-12 17:31 UTC, aleXOR2 commented on test/test_pytest_pylint_xdist_vcs.py
> +TRUE = True
Auto generated test case. I aim to create assets folder during the refactoring upon the 0.1.0 release

2019-12-12 17:32 UTC, aleXOR2 commented on README.md
> +* Python3.5+
Done

2019-12-12 17:33 UTC, aleXOR2 commented on .pre-commit-config.yaml
> +        language_version: python3.6
It is definite python version to run linter checks on CI. If you look at CI lint job - python 3.6 specified there

2020-01-27 11:14 UTC, merged